version: "3.3"
services:
  # Is the main system for poke, so do not change
  main:
    build:
      context: .
      dockerfile: ./docker_files/main/Dockerfile
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://poke:poke_naval_army_origin@db:5432/pokectf
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=production
    depends_on:
      - db
    networks:
      - main
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=poke
      - POSTGRES_PASSWORD=poke_naval_army_origin
      - POSTGRES_DB=pokectf
    networks:
      - main
  
  # All challenges come here:
  deadbeef:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: deadbeef
        FLAG: poke{sh0uld_h4ve_writt3n_it_1n_rust}
    ports:
      - "5001:5000"
  printer:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: printer
        FLAG: poke{s0_th4t's_why_th3y_alw4ys_br34k}
    ports:
      - "5002:5000"
  real_fun:
    build:
      dockerfile: ./docker_files/real_fun/Dockerfile
      context: .
      args:
        NAME: real_fun
        FLAG: poke{th1s_w3b_w4s_fun?}
    ports:
      - "5003:5000"
  liars:
    build:
      dockerfile: ./docker_files/liars/Dockerfile
      context: .
      args:
        NAME: liars
        FLAG: poke{0h_y0ur_p4rents_d0nt_h4v3_4_fl4g?}
    ports:
      - "5004:5000"
  json_notation:
    build: ./docker_files/json_notation
    ports:
      - "5005:3000"
  indigestion:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: indigestion
        FLAG: poke{pr31m4ge_r3s1st4nce_4m1rite}
    ports:
      - "5006:5000"
  aes:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: aes
        FLAG: poke{th4t's_affine_c1ph3r_you_g0t_there}
    ports:
      - "5007:5000"
  boxed_in:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: boxed_in
        FLAG: poke{y0u_mu$$t_r34l1ze_th3r3_1$$_n0_b0x}
    ports:
      - "5008:5000"
  go_fast:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: go_fast
        FLAG: poke{s4n1c_w1ns_th3_hung3r_g4m3SS!}
    ports:
      - "5009:5000"
  green_shell:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: green_shell
        FLAG: poke{1t's-4_m3_sh3llc0d10}
    ports:
      - "5010:5000"
  simple_blog:
    build:
      dockerfile: ./docker_files/simple_blog/Dockerfile
      context: .
      args:
        NAME: simple_blog
    ports:
      - "5011:80"
  whats_db:
    build:
      dockerfile: ./docker_files/whats_db/Dockerfile
      context: .
      args:
        NAME: whats_db
        FLAG: poke{psych0l0g1c4l_ATTACHment_1ssu3s}
    ports:
      - "5012:5000"
  syscall:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: syscall
        FLAG: poke{Here's_my_flag_sysc4ll_m3_m4yb3}
    ports:
      - "5013:5000"
  dumb:
    build:
      dockerfile: ./docker_files/base/Dockerfile
      context: .
      args:
        NAME: dumb
        FLAG: poke{1_filt3r3d_the_f0rm4t_str1ing,_b0$$$$}
    ports:
      - "5014:5000"
volumes:
  postgres_data:
networks:
  # main containers should be on a separate network!!!
  main:
  default: